import courseImage from "../assets/img/course.jpg";

export const courses = [
  // Business
  {
    id: "b1",
    category: "business",
    image: courseImage,
    course_name: "Business Strategy: A Comprehensive Guide",
    description:
      "Learn the fundamentals of business strategy and gain the tools to create a successful business plan.",
    rating_count: 4500,
    rating_star: 4.7,
    students: 15400,
    creator: "John Doe",
    updated_date: "5/2023",
    lang: "english",
    actual_price: 99.99,
    discounted_price: 19.99,
    what_you_will_learn: [
      "Develop a business strategy",
      "Market analysis techniques",
      "Competitive analysis",
      "Financial forecasting",
    ],
    content: [
      "Introduction to Business Strategy",
      "Market Research",
      "Competitive Analysis",
      "Financial Planning",
      "Strategy Implementation",
    ],
  },
  {
    id: "b2",
    category: "business",
    image: courseImage,
    course_name: "Marketing Fundamentals: From Beginner to Expert",
    description:
      "Master the basics of marketing and learn advanced strategies to boost your brand.",
    rating_count: 3200,
    rating_star: 4.5,
    students: 10200,
    creator: "Jane Smith",
    updated_date: "7/2023",
    lang: "english",
    actual_price: 89.99,
    discounted_price: 15.99,
    what_you_will_learn: [
      "Understand marketing principles",
      "Create effective marketing campaigns",
      "Analyze market trends",
      "Digital marketing strategies",
    ],
    content: [
      "Introduction to Marketing",
      "Market Segmentation",
      "Consumer Behavior",
      "Marketing Campaigns",
      "Digital Marketing",
    ],
  },

  // Creativity
  {
    id: "c1",
    category: "creativity",
    image: courseImage,
    course_name: "Creative Writing: Unlock Your Imagination",
    description:
      "Enhance your creative writing skills and learn to craft compelling stories and characters.",
    rating_count: 2800,
    rating_star: 4.6,
    students: 9200,
    creator: "Alice Johnson",
    updated_date: "8/2023",
    lang: "english",
    actual_price: 59.99,
    discounted_price: 12.99,
    what_you_will_learn: [
      "Develop unique story ideas",
      "Create well-rounded characters",
      "Master narrative techniques",
      "Edit and revise your work",
    ],
    content: [
      "Introduction to Creative Writing",
      "Character Development",
      "Plot Structure",
      "Dialogue and Voice",
      "Revising Your Work",
    ],
  },
  {
    id: "c2",
    category: "creativity",
    image: courseImage,
    course_name: "Graphic Design: From Basics to Advanced",
    description:
      "Learn graphic design principles and software to create stunning visual designs.",
    rating_count: 3700,
    rating_star: 4.8,
    students: 15400,
    creator: "Michael Lee",
    updated_date: "9/2023",
    lang: "english",
    actual_price: 74.99,
    discounted_price: 14.99,
    what_you_will_learn: [
      "Design principles and theory",
      "Use graphic design software",
      "Create visual content for print and web",
      "Portfolio development",
    ],
    content: [
      "Introduction to Graphic Design",
      "Design Software Overview",
      "Typography and Color Theory",
      "Creating Visual Content",
      "Portfolio Building",
    ],
  },

  // Language
  {
    id: "l1",
    category: "language",
    image: courseImage,
    course_name: "Spanish for Beginners: A Complete Guide",
    description:
      "Learn the basics of Spanish and start speaking the language confidently.",
    rating_count: 4100,
    rating_star: 4.6,
    students: 17500,
    creator: "Maria Garcia",
    updated_date: "6/2023",
    lang: "english",
    actual_price: 54.99,
    discounted_price: 11.99,
    what_you_will_learn: [
      "Basic Spanish vocabulary",
      "Simple sentence structures",
      "Conversational Spanish",
      "Grammar and pronunciation",
    ],
    content: [
      "Introduction to Spanish",
      "Basic Vocabulary",
      "Simple Sentences",
      "Common Phrases",
      "Conversational Practice",
    ],
  },
  {
    id: "l2",
    category: "language",
    image: courseImage,
    course_name: "Mastering French: Intermediate Level",
    description:
      "Improve your French language skills with this comprehensive intermediate course.",
    rating_count: 2900,
    rating_star: 4.7,
    students: 12300,
    creator: "Jean Dupont",
    updated_date: "7/2023",
    lang: "english",
    actual_price: 69.99,
    discounted_price: 13.99,
    what_you_will_learn: [
      "Advanced French grammar",
      "Complex sentence structures",
      "French conversation practice",
      "French culture and idioms",
    ],
    content: [
      "Intermediate French Grammar",
      "Complex Sentences",
      "French Idioms",
      "Conversation Practice",
      "French Culture",
    ],
  },

  // Law
  {
    id: "l3",
    category: "law",
    image: courseImage,
    course_name: "Introduction to Criminal Law",
    description:
      "Understand the basics of criminal law and its application in real-world scenarios.",
    rating_count: 3400,
    rating_star: 4.5,
    students: 14500,
    creator: "David Williams",
    updated_date: "5/2023",
    lang: "english",
    actual_price: 79.99,
    discounted_price: 16.99,
    what_you_will_learn: [
      "Principles of criminal law",
      "Types of crimes",
      "Legal procedures and courts",
      "Criminal justice system",
    ],
    content: [
      "Criminal Law Overview",
      "Types of Crimes",
      "Legal Procedures",
      "Court Systems",
      "Criminal Justice",
    ],
  },
  {
    id: "l4",
    category: "law",
    image: courseImage,
    course_name: "Contract Law: The Essentials",
    description:
      "Learn the fundamentals of contract law and how to draft and enforce contracts.",
    rating_count: 2900,
    rating_star: 4.6,
    students: 13200,
    creator: "Emily Brown",
    updated_date: "8/2023",
    lang: "english",
    actual_price: 69.99,
    discounted_price: 14.99,
    what_you_will_learn: [
      "Contract formation",
      "Terms and conditions",
      "Contract enforcement",
      "Dispute resolution",
    ],
    content: [
      "Introduction to Contract Law",
      "Contract Formation",
      "Terms and Conditions",
      "Enforcement of Contracts",
      "Dispute Resolution",
    ],
  },

  // Psychology
  {
    id: "p1",
    category: "psychology",
    image: courseImage,
    course_name: "Introduction to Psychology",
    description: "Explore the fundamentals of psychology and human behavior.",
    rating_count: 4200,
    rating_star: 4.7,
    students: 18700,
    creator: "Sara Mitchell",
    updated_date: "6/2023",
    lang: "english",
    actual_price: 79.99,
    discounted_price: 17.99,
    what_you_will_learn: [
      "Basics of psychology",
      "Human behavior and cognition",
      "Psychological disorders",
      "Therapeutic techniques",
    ],
    content: [
      "Psychology Overview",
      "Human Behavior",
      "Cognitive Processes",
      "Psychological Disorders",
      "Therapeutic Approaches",
    ],
  },
  {
    id: "p2",
    category: "psychology",
    image: courseImage,
    course_name: "Cognitive Psychology: Understanding the Mind",
    description:
      "Dive deep into cognitive psychology and understand how the mind processes information.",
    rating_count: 3100,
    rating_star: 4.6,
    students: 11600,
    creator: "Michael Johnson",
    updated_date: "9/2023",
    lang: "english",
    actual_price: 84.99,
    discounted_price: 19.99,
    what_you_will_learn: [
      "Cognitive processes",
      "Memory and learning",
      "Problem-solving and decision-making",
      "Cognitive development",
    ],
    content: [
      "Introduction to Cognitive Psychology",
      "Memory and Learning",
      "Problem-Solving",
      "Decision-Making",
      "Cognitive Development",
    ],
  },

  // Additional Categories
  {
    id: "a1",
    category: "art",
    image: courseImage,
    course_name: "Art Fundamentals: Drawing and Painting Techniques",
    description:
      "Learn essential techniques for drawing and painting in various mediums.",
    rating_count: 2200,
    rating_star: 4.6,
    students: 9800,
    creator: "Laura Adams",
    updated_date: "7/2023",
    lang: "english",
    actual_price: 64.99,
    discounted_price: 13.99,
    what_you_will_learn: [
      "Basic drawing techniques",
      "Painting techniques",
      "Color theory",
      "Artistic styles",
    ],
    content: [
      "Drawing Basics",
      "Painting Techniques",
      "Color Theory",
      "Artistic Styles",
      "Creating Artworks",
    ],
  },
  {
    id: "a2",
    category: "art",
    image: courseImage,
    course_name: "Digital Art Creation: Tools and Techniques",
    description:
      "Explore digital art tools and techniques to create stunning digital artworks.",
    rating_count: 2800,
    rating_star: 4.7,
    students: 11200,
    creator: "James Carter",
    updated_date: "8/2023",
    lang: "english",
    actual_price: 89.99,
    discounted_price: 19.99,
    what_you_will_learn: [
      "Digital art tools and software",
      "Techniques for digital drawing",
      "Creating digital illustrations",
      "Graphic design basics",
    ],
    content: [
      "Introduction to Digital Art Tools",
      "Digital Drawing Techniques",
      "Creating Illustrations",
      "Graphic Design Basics",
      "Portfolio Development",
    ],
  },
  {
    id: "s1",
    category: "science",
    image: courseImage,
    course_name: "Introduction to Environmental Science",
    description:
      "Learn about environmental science, focusing on ecological principles and environmental issues.",
    rating_count: 3400,
    rating_star: 4.6,
    students: 14000,
    creator: "Dr. Alice Green",
    updated_date: "7/2023",
    lang: "english",
    actual_price: 74.99,
    discounted_price: 14.99,
    what_you_will_learn: [
      "Basic ecological principles",
      "Environmental issues and challenges",
      "Sustainable practices",
      "Environmental policy",
    ],
    content: [
      "Introduction to Ecology",
      "Environmental Issues",
      "Sustainability",
      "Environmental Policy",
      "Case Studies",
    ],
  },
  {
    id: "s2",
    category: "science",
    image: courseImage,
    course_name: "Physics Fundamentals: From Classical to Quantum",
    description:
      "Explore the fundamentals of physics, from classical mechanics to quantum theory.",
    rating_count: 2900,
    rating_star: 4.7,
    students: 11500,
    creator: "Dr. Robert White",
    updated_date: "8/2023",
    lang: "english",
    actual_price: 89.99,
    discounted_price: 19.99,
    what_you_will_learn: [
      "Classical mechanics",
      "Electromagnetism",
      "Thermodynamics",
      "Quantum mechanics",
    ],
    content: [
      "Classical Mechanics",
      "Electromagnetism",
      "Thermodynamics",
      "Quantum Mechanics",
      "Advanced Topics",
    ],
  },
  {
    id: "t1",
    category: "technology",
    image: courseImage,
    course_name: "Introduction to Machine Learning",
    description:
      "Understand the basics of machine learning and how to implement simple models.",
    rating_count: 5000,
    rating_star: 4.8,
    students: 21000,
    creator: "Dr. Laura Evans",
    updated_date: "9/2023",
    lang: "english",
    actual_price: 79.99,
    discounted_price: 17.99,
    what_you_will_learn: [
      "Fundamentals of machine learning",
      "Types of machine learning models",
      "Model evaluation techniques",
      "Hands-on projects",
    ],
    content: [
      "Introduction to Machine Learning",
      "Supervised Learning",
      "Unsupervised Learning",
      "Model Evaluation",
      "Hands-on Projects",
    ],
  },
  {
    id: "t2",
    category: "technology",
    image: courseImage,
    course_name: "Introduction to Cybersecurity",
    description:
      "Learn the essentials of cybersecurity and how to protect systems from threats.",
    rating_count: 4200,
    rating_star: 4.6,
    students: 17000,
    creator: "Dr. Michael Harris",
    updated_date: "7/2023",
    lang: "english",
    actual_price: 84.99,
    discounted_price: 19.99,
    what_you_will_learn: [
      "Cybersecurity fundamentals",
      "Common security threats",
      "Security best practices",
      "Incident response",
    ],
    content: [
      "Introduction to Cybersecurity",
      "Security Threats",
      "Protection Techniques",
      "Incident Response",
      "Case Studies",
    ],
  },
  {
    id: "m1",
    category: "mathematics",
    image: courseImage,
    course_name: "Calculus I: Limits and Derivatives",
    description:
      "Learn the fundamental concepts of calculus including limits and derivatives.",
    rating_count: 3700,
    rating_star: 4.7,
    students: 15900,
    creator: "Dr. Emily Brown",
    updated_date: "8/2023",
    lang: "english",
    actual_price: 74.99,
    discounted_price: 16.99,
    what_you_will_learn: [
      "Concepts of limits",
      "Differentiation techniques",
      "Applications of derivatives",
      "Graphing functions",
    ],
    content: [
      "Introduction to Limits",
      "Differentiation Techniques",
      "Applications of Derivatives",
      "Graphing Functions",
      "Practice Problems",
    ],
  },
  {
    id: "m2",
    category: "mathematics",
    image: courseImage,
    course_name: "Linear Algebra: Vectors and Matrices",
    description:
      "Understand the basics of linear algebra including vector spaces and matrix operations.",
    rating_count: 3400,
    rating_star: 4.6,
    students: 12200,
    creator: "Dr. John Davis",
    updated_date: "7/2023",
    lang: "english",
    actual_price: 64.99,
    discounted_price: 14.99,
    what_you_will_learn: [
      "Vector spaces",
      "Matrix operations",
      "Linear transformations",
      "Eigenvalues and eigenvectors",
    ],
    content: [
      "Introduction to Vectors",
      "Matrix Operations",
      "Linear Transformations",
      "Eigenvalues and Eigenvectors",
      "Applications",
    ],
  },
];
